"""
Public API surface for the ai module. Re-exports all types, providers, streaming
functions, and utilities used by agent and coding_agent layers.

Owns: the canonical import path for everything in nuu.ai.
Delegates to: each submodule for implementation.

Depends on: nuu.ai.api_registry, nuu.ai.event_stream, nuu.ai.models,
  nuu.ai.stream, nuu.ai.types, nuu.ai.validation, nuu.ai.providers
"""

from .api_registry import (
    ApiProvider,
    register_api_provider,
    get_api_provider,
    get_api_providers,
    clear_api_providers,
)
from .event_stream import EventStream, AssistantMessageEventStream
from .models import (
    load_models,
    register_model,
    get_model,
    get_providers,
    get_models,
    calculate_cost,
    get_supported_thinking_levels,
    clamp_thinking_level,
)
from .stream import stream, complete, stream_simple, complete_simple
from .types import (
    KnownApi,
    KnownProvider,
    Api,
    Provider,
    ModelInfo,
    ModelCost,
    Usage,
    UsageCost,
    Context,
    Message,
    UserMessage,
    AssistantMessage,
    ToolResultMessage,
    Tool,
    ToolCall,
    TextContent,
    ThinkingContent,
    ImageContent,
    StreamOptions,
    SimpleStreamOptions,
    AssistantMessageEvent,
    StartEvent,
    TextStartEvent,
    TextDeltaEvent,
    TextEndEvent,
    ThinkingStartEvent,
    ThinkingDeltaEvent,
    ThinkingEndEvent,
    ToolCallStartEvent,
    ToolCallDeltaEvent,
    ToolCallEndEvent,
    DoneEvent,
    ErrorEvent,
    ThinkingLevel,
    ModelThinkingLevel,
    ThinkingLevelMap,
    ThinkingBudgets,
    CacheRetention,
    StopReason,
    Transport,
    OpenAICompletionsCompat,
    OpenAIResponsesCompat,
    AnthropicMessagesCompat,
    ProviderResponse,
    OpenRouterRouting,
    VercelGatewayRouting,
    AssistantMessageDiagnostic,
)
from .validation import validate_tool_arguments, validate_tool_call

from . import providers
from .providers import register_builtins  # noqa: F401
from . import cli
from . import env_api_keys
from . import session_resources
from . import utils

__all__ = [
    "ApiProvider",
    "register_api_provider",
    "get_api_provider",
    "get_api_providers",
    "clear_api_providers",
    "EventStream",
    "AssistantMessageEventStream",
    "load_models",
    "register_model",
    "get_model",
    "get_providers",
    "get_models",
    "calculate_cost",
    "get_supported_thinking_levels",
    "clamp_thinking_level",
    "stream",
    "complete",
    "stream_simple",
    "complete_simple",
    "KnownApi",
    "KnownProvider",
    "Api",
    "Provider",
    "ModelInfo",
    "ModelCost",
    "Usage",
    "UsageCost",
    "Context",
    "Message",
    "UserMessage",
    "AssistantMessage",
    "ToolResultMessage",
    "Tool",
    "ToolCall",
    "TextContent",
    "ThinkingContent",
    "ImageContent",
    "StreamOptions",
    "SimpleStreamOptions",
    "AssistantMessageEvent",
    "StartEvent",
    "TextStartEvent",
    "TextDeltaEvent",
    "TextEndEvent",
    "ThinkingStartEvent",
    "ThinkingDeltaEvent",
    "ThinkingEndEvent",
    "ToolCallStartEvent",
    "ToolCallDeltaEvent",
    "ToolCallEndEvent",
    "DoneEvent",
    "ErrorEvent",
    "ThinkingLevel",
    "ModelThinkingLevel",
    "ThinkingLevelMap",
    "ThinkingBudgets",
    "CacheRetention",
    "StopReason",
    "Transport",
    "OpenAICompletionsCompat",
    "OpenAIResponsesCompat",
    "AnthropicMessagesCompat",
    "ProviderResponse",
    "OpenRouterRouting",
    "VercelGatewayRouting",
    "AssistantMessageDiagnostic",
    "validate_tool_arguments",
    "validate_tool_call",
    "providers",
    "cli",
    "env_api_keys",
    "session_resources",
    "utils",
]
